title: Hello World! I am Zadid!
description: > # this means to ignore newlines until "baseurl:"
  This is a personal blog. I write about whatever interests me. Hope my thoughts will help others gain some perspectives as well.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zahidul-hasan.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Md Zahidul Hasan # add your name
author-img: pic.jpg #david-freeman.jpg # add your photo
about-author: Lecturer, Department of Computer Science and Engineering, BRAC University, Bangladesh. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: https://github.com/Zahidul-Hasan # add your Github handle
social-linkedin: https://www.linkedin.com/in/mohammad-zahidul-hasan-09223517b/# add your Linkedin handle
social-email: zadidhasan11@gmail.com# add your Email address
theme-name: flexible-jekyll
# Disqus
#discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-katex

paginate: 10
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
